import type { CatalogFile } from "./schema.js";

const allPlatforms = ["darwin", "linux", "win32"] as const;

export const defaultCatalog: CatalogFile = {
  schemaVersion: 1,
  entries: [
    {
      id: "claude-code",
      name: "Claude Code",
      summary: "Anthropic's agentic coding tool for the terminal.",
      publisher: { name: "Anthropic", url: "https://anthropic.com", verified: true },
      kind: "detected-cli",
      platforms: [...allPlatforms],
      capabilities: ["chat", "coding", "tools", "local-files"],
      permissions: ["Execute a local CLI", "Read and modify files in the selected workspace"],
      homepage: "https://docs.anthropic.com/en/docs/claude-code",
      license: "Proprietary",
      descriptorId: "claude-code",
      installRecipes: [
        { method: "brew", executable: "brew", args: ["install", "claude"], requiresElevation: false },
        { method: "npm", executable: "npm", args: ["install", "-g", "@anthropic-ai/claude-code"], requiresElevation: false },
      ],
      uninstallRecipes: [
        { method: "brew", executable: "brew", args: ["uninstall", "claude"], requiresElevation: false },
        { method: "npm", executable: "npm", args: ["uninstall", "-g", "@anthropic-ai/claude-code"], requiresElevation: false },
      ],
      adapterTemplate: {
        type: "cli",
        config: { input: "argument", output: "jsonl", args: ["-p", "--output-format", "stream-json", "--verbose", "--no-session-persistence"] },
      },
    },
    {
      id: "codex",
      name: "Codex",
      summary: "OpenAI's coding agent for the terminal.",
      publisher: { name: "OpenAI", url: "https://openai.com", verified: true },
      kind: "detected-cli",
      platforms: [...allPlatforms],
      capabilities: ["chat", "coding", "tools", "local-files"],
      permissions: ["Execute a local CLI", "Read and modify files in the selected workspace"],
      homepage: "https://developers.openai.com/codex/cli",
      license: "Apache-2.0",
      descriptorId: "codex",
      installRecipes: [
        { method: "npm", executable: "npm", args: ["install", "-g", "@openai/codex"], requiresElevation: false },
      ],
      uninstallRecipes: [
        { method: "npm", executable: "npm", args: ["uninstall", "-g", "@openai/codex"], requiresElevation: false },
      ],
      adapterTemplate: { type: "cli", config: { input: "argument", output: "codex-json", args: ["exec", "--json"] } },
    },
    {
      id: "copilot-cli",
      name: "GitHub Copilot CLI",
      summary: "GitHub Copilot's coding agent for your terminal.",
      publisher: { name: "GitHub", url: "https://github.com", verified: true },
      kind: "detected-cli",
      platforms: [...allPlatforms],
      capabilities: ["chat", "coding", "tools", "local-files"],
      permissions: ["Execute a local CLI", "Read and modify files in the selected workspace"],
      homepage: "https://github.com/features/copilot/cli",
      license: "Proprietary",
      descriptorId: "copilot-cli",
      installRecipes: [
        { method: "npm", executable: "npm", args: ["install", "-g", "@github/copilot-cli"], requiresElevation: false },
      ],
      uninstallRecipes: [
        { method: "npm", executable: "npm", args: ["uninstall", "-g", "@github/copilot-cli"], requiresElevation: false },
      ],
      adapterTemplate: { type: "cli", config: { input: "argument", output: "plain", args: ["-p"] } },
    },
    {
      id: "gemini-cli",
      name: "Gemini CLI",
      summary: "Google's AI coding agent for the terminal.",
      publisher: { name: "Google", url: "https://google.com", verified: true },
      kind: "detected-cli",
      platforms: [...allPlatforms],
      capabilities: ["chat", "coding", "tools", "local-files"],
      permissions: ["Execute a local CLI", "Read and modify files in the selected workspace"],
      homepage: "https://github.com/google-gemini/gemini-cli",
      license: "Apache-2.0",
      descriptorId: "gemini-cli",
      installRecipes: [
        { method: "npm", executable: "npm", args: ["i", "-g", "@google/gemini-cli"], requiresElevation: false },
      ],
      uninstallRecipes: [
        { method: "npm", executable: "npm", args: ["uninstall", "-g", "@google/gemini-cli"], requiresElevation: false },
      ],
      adapterTemplate: { type: "cli", config: { input: "argument", output: "jsonl", args: ["--json"] } },
    },
    {
      id: "aider",
      name: "Aider",
      summary: "AI pair programming in your terminal.",
      publisher: { name: "Paul Gauthier", url: "https://aider.chat", verified: true },
      kind: "detected-cli",
      platforms: [...allPlatforms],
      capabilities: ["chat", "coding", "tools", "local-files"],
      permissions: ["Execute a local CLI", "Read and modify files in the selected workspace"],
      homepage: "https://aider.chat",
      license: "Apache-2.0",
      descriptorId: "aider",
      installRecipes: [
        { method: "pip", executable: "pip", args: ["install", "aider-chat"], requiresElevation: false },
      ],
      uninstallRecipes: [
        { method: "pip", executable: "pip", args: ["uninstall", "-y", "aider-chat"], requiresElevation: false },
      ],
      adapterTemplate: { type: "cli", config: { input: "stdin", output: "plain", args: ["--no-auto-commits", "--stream"] } },
    },
    {
      id: "qwen-code",
      name: "Qwen Code",
      summary: "Qwen's AI coding agent for the terminal.",
      publisher: { name: "Alibaba/Qwen", url: "https://github.com/QwenLM", verified: true },
      kind: "detected-cli",
      platforms: [...allPlatforms],
      capabilities: ["chat", "coding", "tools", "local-files"],
      permissions: ["Execute a local CLI", "Read and modify files in the selected workspace"],
      homepage: "https://github.com/QwenLM/Qwen",
      license: "Apache-2.0",
      descriptorId: "qwen-code",
      installRecipes: [
        { method: "pip", executable: "pip", args: ["install", "qwen-code"], requiresElevation: false },
      ],
      uninstallRecipes: [
        { method: "pip", executable: "pip", args: ["uninstall", "-y", "qwen-code"], requiresElevation: false },
      ],
      adapterTemplate: { type: "cli", config: { input: "argument", output: "plain", args: ["--no-stream"] } },
    },
    {
      id: "cursor-cli",
      name: "Cursor CLI",
      summary: "Cursor's AI coding agent for the terminal.",
      publisher: { name: "Cursor", url: "https://cursor.sh", verified: true },
      kind: "detected-cli",
      platforms: [...allPlatforms],
      capabilities: ["chat", "coding", "tools", "local-files"],
      permissions: ["Execute a local CLI", "Read and modify files in the selected workspace"],
      homepage: "https://cursor.sh",
      license: "Proprietary",
      descriptorId: "cursor-cli",
      installRecipes: [
        { method: "npm", executable: "npm", args: ["i", "-g", "@cursor-ai/cli"], requiresElevation: false },
      ],
      uninstallRecipes: [
        { method: "npm", executable: "npm", args: ["uninstall", "-g", "@cursor-ai/cli"], requiresElevation: false },
      ],
      adapterTemplate: { type: "cli", config: { input: "argument", output: "jsonl", args: ["--json"] } },
    },
    {
      id: "openai-api",
      name: "OpenAI API",
      summary: "Connect to OpenAI models using an API key.",
      publisher: { name: "OpenAI", url: "https://openai.com", verified: true },
      kind: "api-connector",
      platforms: [...allPlatforms],
      capabilities: ["chat", "streaming"],
      permissions: ["Connect to api.openai.com", "Store the API key in the local AgentLink database"],
      homepage: "https://platform.openai.com/docs",
      license: "Commercial",
      installRecipes: [],
      uninstallRecipes: [],
      adapterTemplate: { type: "openai", config: { endpoint: "https://api.openai.com/v1", model: "gpt-4o-mini" } },
    },
    {
      id: "deepseek-api",
      name: "DeepSeek API",
      summary: "Connect to DeepSeek's OpenAI-compatible chat API.",
      publisher: { name: "DeepSeek", url: "https://deepseek.com", verified: true },
      kind: "api-connector",
      platforms: [...allPlatforms],
      capabilities: ["chat", "streaming"],
      permissions: ["Connect to api.deepseek.com", "Store the API key in the local AgentLink database"],
      homepage: "https://api-docs.deepseek.com",
      license: "Commercial",
      installRecipes: [],
      uninstallRecipes: [],
      adapterTemplate: { type: "openai", config: { endpoint: "https://api.deepseek.com/v1", model: "deepseek-chat" } },
    },
    {
      id: "glm-api",
      name: "GLM API",
      summary: "Connect to Zhipu AI's OpenAI-compatible GLM API.",
      publisher: { name: "Zhipu AI", url: "https://z.ai", verified: true },
      kind: "api-connector",
      platforms: [...allPlatforms],
      capabilities: ["chat", "streaming"],
      permissions: ["Connect to open.bigmodel.cn", "Store the API key in the local AgentLink database"],
      homepage: "https://docs.bigmodel.cn",
      license: "Commercial",
      installRecipes: [],
      uninstallRecipes: [],
      adapterTemplate: { type: "openai", config: { endpoint: "https://open.bigmodel.cn/api/paas/v4", model: "glm-4-flash" } },
    },
  ],
};
